Server:
  RunMode: debug
  HttpPort: 8083
  ReadTimeout: 60s #要带上单位
  WriteTimeout: 60s
log :
  Filename  : tag_sight.log
  level : DEBUG
  MaxSize : 10 #mb
  MaxBackups :  10 #能保留的文件的最多的数量
  MaxAge    : 30 #保留的最大天数
mysql:
  Username: root   # 填写你的数据库账号
  Password: 123456 # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: tag_sight
  MaxIdleConns: 30
  MaxOpenConns: 100

jwt:
  # 设置jwt签名加密时使用的秘钥
  secret: user
  # 设置jwt过期时间
  ttl: 7200000
  # 设置前端传递过来的令牌名称
  name: Authorization

